# Generated by Django 5.2.3 on 2025-06-23 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Bag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bag_number", models.CharField(max_length=50, unique=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in kilograms", max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sorted_at", models.DateTimeField(blank=True, null=True)),
                ("is_sorted", models.BooleanField(default=False)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepared_bags",
                        to="sortapp.employee",
                    ),
                ),
                (
                    "sorted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sorted_bags",
                        to="sortapp.employee",
                    ),
                ),
            ],
        ),
    ]
