# Generated by Django 5.2.3 on 2025-06-27 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortapp", "0002_bag_ean_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Pracownik", "verbose_name_plural": "Pracownicy"},
        ),
        migrations.RemoveField(
            model_name="bag",
            name="ean_code",
        ),
        migrations.AddField(
            model_name="bag",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="bag_number",
            field=models.CharField(
                help_text="Unikalny identyfikator torby (taki sam jak kod EAN)",
                max_length=50,
                unique=True,
                verbose_name="Numer torby",
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data utworzenia"
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="is_sorted",
            field=models.BooleanField(default=False, verbose_name="Posortowane"),
        ),
        migrations.AlterField(
            model_name="bag",
            name="prepared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prepared_bags",
                to="sortapp.employee",
                verbose_name="Przygotowane przez",
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="sorted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data sortowania"
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="sorted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sorted_bags",
                to="sortapp.employee",
                verbose_name="Posortowane przez",
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Waga w kilogramach",
                max_digits=6,
                verbose_name="Waga",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Imię i nazwisko"),
        ),
    ]
