# Generated by Django 5.2.3 on 2025-06-27 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sortapp", "0003_alter_employee_options_remove_bag_ean_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bag",
            name="prepared_by",
        ),
    ]
