# Generated by Django 5.2.3 on 2025-06-27 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortapp", "0004_remove_bag_prepared_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingClothing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Klasa ikony Font Awesome, np. 'fa-tshirt'",
                        max_length=50,
                        verbose_name="Ikona",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        help_text="Kolor w formacie HEX, np. '#3498db'",
                        max_length=20,
                        verbose_name="Kolor",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktywna")),
            ],
            options={
                "verbose_name": "Odzież przychodząca",
                "verbose_name_plural": "Odzież przychodząca",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="bag",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bags",
                to="sortapp.employee",
                verbose_name="Przydzielone do",
            ),
        ),
        migrations.AddField(
            model_name="bag",
            name="prepared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prepared_bags",
                to="sortapp.employee",
                verbose_name="Przygotowane przez",
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Waga w kilogramach",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Waga",
            ),
        ),
        migrations.AddField(
            model_name="bag",
            name="clothing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bags",
                to="sortapp.incomingclothing",
                verbose_name="Rodzaj odzieży",
            ),
        ),
    ]
