# Generated by Django 5.2.3 on 2025-06-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortapp", "0005_incomingclothing_bag_assigned_to_bag_prepared_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bag",
            name="prepared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prepared_bags",
                to="sortapp.employee",
                verbose_name="Przygotowane przez",
            ),
        ),
    ]
