# Generated by Django 5.2.3 on 2025-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortapp", "0006_alter_bag_prepared_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="icon_color",
            field=models.CharField(
                default="#3498db",
                help_text="Kolor ikony pracownika w formacie HEX, np. '#3498db'",
                max_length=20,
                verbose_name="Kolor ikony",
            ),
        ),
    ]
