# Generated by Django 5.2.3 on 2025-06-27 10:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortapp", "0007_employee_icon_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SortedClothingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Klasa ikony Font Awesome, np. 'fa-tshirt'",
                        max_length=50,
                        verbose_name="Ikona",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        help_text="Kolor w formacie HEX, np. '#3498db'",
                        max_length=20,
                        verbose_name="Kolor",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktywna")),
            ],
            options={
                "verbose_name": "Kategoria posortowanej odzieży",
                "verbose_name_plural": "Kategorie posortowanej odzieży",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SortedBag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bag_number",
                    models.CharField(
                        help_text="Unikalny identyfikator torby (taki sam jak kod EAN)",
                        max_length=50,
                        unique=True,
                        verbose_name="Numer torby",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Waga w kilogramach",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Waga",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data utworzenia",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorted_bags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "original_bag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulting_sorted_bags",
                        to="sortapp.bag",
                        verbose_name="Worek źródłowy",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_sorted_bags",
                        to="sortapp.employee",
                        verbose_name="Przygotowane przez",
                    ),
                ),
                (
                    "clothing_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorted_bags",
                        to="sortapp.sortedclothingcategory",
                        verbose_name="Kategoria odzieży",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posortowana torba",
                "verbose_name_plural": "Posortowane torby",
                "ordering": ["-created_at"],
            },
        ),
    ]
