# Generated by Django 5.2.3 on 2025-07-03 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortapp", "0008_sortedclothingcategory_sortedbag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sortedbag",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data zamknięcia"
            ),
        ),
        migrations.AddField(
            model_name="sortedbag",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Zamknięty"),
        ),
        migrations.AlterField(
            model_name="sortedbag",
            name="bag_number",
            field=models.CharField(
                blank=True,
                help_text="Unikalny identyfikator torby (taki sam jak kod EAN)",
                max_length=50,
                unique=True,
                verbose_name="Numer torby",
            ),
        ),
        migrations.CreateModel(
            name="SortedBagWeightHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Poprzednia waga"
                    ),
                ),
                (
                    "new_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Nowa waga"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data zmiany"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="Finalna waga"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Uwagi"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weight_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Zmienione przez",
                    ),
                ),
                (
                    "sorted_bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_history",
                        to="sortapp.sortedbag",
                        verbose_name="Posortowana torba",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia wagi torby",
                "verbose_name_plural": "Historia wag toreb",
                "ordering": ["-changed_at"],
            },
        ),
    ]
