# Generated by Django 5.2.3 on 2025-07-04 08:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortapp", "0009_sortedbag_closed_at_sortedbag_is_closed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bag",
            name="prepared_by",
        ),
        migrations.AlterField(
            model_name="bag",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Data utworzenia",
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="is_sorted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Posortowane"
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="sorted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Data sortowania"
            ),
        ),
        migrations.AlterField(
            model_name="sortedbag",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Data zamknięcia"
            ),
        ),
        migrations.AlterField(
            model_name="sortedbag",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Data utworzenia",
            ),
        ),
        migrations.AlterField(
            model_name="sortedbag",
            name="is_closed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Zamknięty"
            ),
        ),
        migrations.AlterField(
            model_name="sortedbagweighthistory",
            name="changed_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Data zmiany",
            ),
        ),
        migrations.AlterField(
            model_name="sortedbagweighthistory",
            name="is_final",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Finalna waga"
            ),
        ),
        migrations.AddIndex(
            model_name="sortedbag",
            index=models.Index(
                fields=["created_at", "clothing_category"],
                name="sortapp_sor_created_ec6104_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sortedbag",
            index=models.Index(
                fields=["prepared_by", "created_at"],
                name="sortapp_sor_prepare_78390c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sortedbagweighthistory",
            index=models.Index(
                fields=["sorted_bag", "changed_at"],
                name="sortapp_sor_sorted__a28b23_idx",
            ),
        ),
    ]
